name: Linter

on:
  workflow_dispatch:
  pull_request:

jobs:
  lint:
    uses: swrlab/node-utils/.github/workflows/linter.yml@a429639efca859a672387913f67b7413874881ba
    with:
      install-all: false
      generate-keys: false
      skip-checkout: false
