---
name: Linter

on:
  pull_request:

env:
  DEFAULT_BRANCH: main
  EDITORCONFIG_FILE_NAME: /.editorconfig
  IGNORE_GITIGNORED_FILES: true
  JAVASCRIPT_DEFAULT_STYLE: prettier
  JAVASCRIPT_ES_CONFIG_FILE: /.eslintrc.json
  LINTER_RULES_PATH: /
  LOG_LEVEL: VERBOSE
  MARKDOWN_CONFIG_FILE: /.markdownlint.yaml
  NODE_VERSION: 18
  VALIDATE_ALL_CODEBASE: true
  YAML_CONFIG_FILE: /.github/linters/.yamllint.yaml

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    timeout-minutes: 70
    steps:
      - name: 👀 Checkout repo
        uses: actions/checkout@v3

      - name: ⛺️ Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - name: 📦 Install Dependencies
        run: yarn

      - name: 📚 Lint Code Base
        uses: docker://github/super-linter:v4
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
