name: Linter

on:
  workflow_dispatch:
  pull_request:

jobs:
  lint:
    uses: swrlab/node-utils/.github/workflows/linter.yml@main
    with:
      install-all: false
      generate-keys: false
      log-level: 'NOTICE'
